//HintName: _ServiceCollectionExtensions.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Ravitor.Generator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Ravitor.Contracts.Handlers;

namespace Microsoft.Extensions.DependencyInjection;

internal static class ServiceCollectionExtensions
{
    public static IServiceCollection AddRavitorHandlers(this IServiceCollection services)
    {
        services.AddScoped<global::Some.Nested.Types.Program.PingHandler>();
        services.AddScoped<global::Ravitor.Generator.Some.Nested.Types.Program_PingHandlerWrapper>();
        services.AddScoped<IRequestHandler<global::Some.Nested.Types.Program.Ping, global::Some.Nested.Types.Program.Pong>, global::Ravitor.Generator.Some.Nested.Types.Program_PingHandlerWrapper>(static sp => sp.GetRequiredService<global::Ravitor.Generator.Some.Nested.Types.Program_PingHandlerWrapper>());

        return services;
    }
}

#nullable disable
