namespace Blackwing;

internal static class Constants
{


    public static class Assembly
    {
        public const string Name = "Blackwing.Contracts";
    }

    public static class BuildProperties
    {
        public const string DisableBlackwingInterceptor = "build_property.DisableBlackwingInterceptor";
    }

    public static class Options
    {
        public const string AttributeFullName = "Blackwing.Contracts.Options.BlackwingOptionsAttribute";
    }

    public static class Generator
    {
        public const string Namespace = "Blackwing.Generator";

        public const string Header = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by the Blackwing.Generator source generator
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable
        """;

        public const string Footer = """
        #nullable disable
        """;
    }

    public static class Requests
    {
        public const string InterceptorFile = "_Interceptor.g.cs";
        public const string ServiceCollectionFile = "_ServiceCollectionExtensions.g.cs";

        public const string Namespace = "Blackwing.Contracts.Requests";

        public const string IRequest = "IRequest";
        public const string IRequestFull = "Blackwing.Contracts.Requests.IRequest";

        public const string IRequestHandler = "IRequestHandler";
        public const string IRequestHandlerFull = "Blackwing.Contracts.Handlers.IRequestHandler";

        public const string IRequestPipeline = "IRequestPipeline";
        public const string IRequestPipelineFull = "Blackwing.Contracts.Pipelines.IRequestPipeline";
        public const string IRequestPipelineDelegate = "IRequestPipelineDelegate";
    }

    public static class Contracts
    {
        public const string Namespace = "Blackwing.Contracts";

        public const string IMediator = "IMediator";
        public const string IMediatorFull = "Blackwing.Contracts.IMediator";

        public const string ISender = "ISender";
        public const string ISenderFull = "Blackwing.Contracts.ISender";

        public const string ISender_SendMethod = "Send";
    }
}
