//HintName: Blackwing_Test_Integration_PingCommandHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Blackwing.Generator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Blackwing.Contracts.Requests;
using Microsoft.Extensions.DependencyInjection;

namespace Blackwing.Generator.Blackwing.Test.Integration;

internal sealed class PingCommandHandlerWrapper : IRequestHandler<global::Blackwing.Test.Integration.Ping, global::Blackwing.Test.Integration.Result<global::Blackwing.Test.Integration.Pong>>
{
    private readonly IRequestPipelineDelegate<global::Blackwing.Test.Integration.Ping, global::Blackwing.Test.Integration.Result<global::Blackwing.Test.Integration.Pong>> handler;

    public PingCommandHandlerWrapper(
        global::Blackwing.Test.Integration.PingCommandHandler handler,
        IEnumerable<IRequestPipeline<global::Blackwing.Test.Integration.Ping, global::Blackwing.Test.Integration.Result<global::Blackwing.Test.Integration.Pong>>> behaviors)
    {
        var finalHandler = (IRequestPipelineDelegate<global::Blackwing.Test.Integration.Ping, global::Blackwing.Test.Integration.Result<global::Blackwing.Test.Integration.Pong>>)handler.Handle;
        foreach (var pipeline in behaviors.Reverse())
        {
            var handlerCopy = finalHandler;
            var pipelineCopy = pipeline;
            finalHandler = (global::Blackwing.Test.Integration.Ping request, CancellationToken cancellationToken) => pipelineCopy.Handle(request, handlerCopy, cancellationToken);
        }
        this.handler = finalHandler;
    }

    public ValueTask<global::Blackwing.Test.Integration.Result<global::Blackwing.Test.Integration.Pong>> Handle(global::Blackwing.Test.Integration.Ping request, CancellationToken cancellationToken = default)
    {
        return handler(request, cancellationToken);
    }
}

#nullable disable
