//HintName: _Interceptor.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Ravitor.Generator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using Ravitor.Contracts.Requests;
using Microsoft.Extensions.DependencyInjection;

namespace System.Runtime.CompilerServices
{
    [Conditional("DEBUG")] // not needed post-build, so can evaporate it
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    sealed file class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}

namespace Ravitor.Generator
{
    static file class Interceptors
    {
        [InterceptsLocation(1, "KnNQv/PXF5xxsoH/WDvS1KYDAAA=")] // (31,32)
        public static ValueTask<TResponse> Send_Some_Very_Very_Very_Very_Deep_Namespace_ThatIUseToTestTheSourceGenSoThatItCanHandleLotsOfDifferentInput_Ping<TResponse>(this global::Ravitor.Services.Mediator sender, IRequest<TResponse> request, CancellationToken cancellationToken = default)
        {
            var rqst = request as global::Some.Very.Very.Very.Very.Deep.Namespace.ThatIUseToTestTheSourceGenSoThatItCanHandleLotsOfDifferentInput.Ping;
            var task = sender.Send<global::Some.Very.Very.Very.Very.Deep.Namespace.ThatIUseToTestTheSourceGenSoThatItCanHandleLotsOfDifferentInput.Ping, global::Some.Very.Very.Very.Very.Deep.Namespace.ThatIUseToTestTheSourceGenSoThatItCanHandleLotsOfDifferentInput.Pong>(rqst!, cancellationToken);
            return Unsafe.As<ValueTask<global::Some.Very.Very.Very.Very.Deep.Namespace.ThatIUseToTestTheSourceGenSoThatItCanHandleLotsOfDifferentInput.Pong>, ValueTask<TResponse>>(ref task);
        }

    }
}

#nullable disable
