//HintName: _Interceptor.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Blackwing.Generator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using Blackwing.Contracts;
using Blackwing.Contracts.Requests;
using Microsoft.Extensions.DependencyInjection;

namespace System.Runtime.CompilerServices
{
    [Conditional("DEBUG")] // not needed post-build, so can evaporate it
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    sealed file class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}

namespace Blackwing.Interceptor
{
    static file class Interceptors
    {
        [InterceptsLocation(1, "Z9Hc7FSS/ewqhSER5HSrYgoDAAA=")] // (29,32)
        public static ValueTask<TResponse> Send_Some_Nested_Types_Program_Ping<TResponse>(this global::Blackwing.Contracts.ISender sender, IRequest<TResponse> request, CancellationToken cancellationToken = default)
        {
            var rqst = request as global::Some.Nested.Types.Program.Ping;
            var task = sender.Send<global::Some.Nested.Types.Program.Ping, global::Some.Nested.Types.Program.Pong>(rqst!, cancellationToken);
            return Unsafe.As<ValueTask<global::Some.Nested.Types.Program.Pong>, ValueTask<TResponse>>(ref task);
        }

    }
}

#nullable disable
