//HintName: Some_Nested_Types_Program_PingHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Blackwing.Generator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Blackwing.Contracts.Requests;
using Microsoft.Extensions.DependencyInjection;

namespace Blackwing.Generator.Some.Nested.Types;

internal sealed class Program_PingHandlerWrapper : IRequestHandler<global::Some.Nested.Types.Program.Ping, global::Some.Nested.Types.Program.Pong>
{
    private readonly IRequestPipelineDelegate<global::Some.Nested.Types.Program.Ping, global::Some.Nested.Types.Program.Pong> handler;

    public Program_PingHandlerWrapper(
        global::Some.Nested.Types.Program.PingHandler handler,
        IEnumerable<IRequestPipeline<global::Some.Nested.Types.Program.Ping, global::Some.Nested.Types.Program.Pong>> behaviors)
    {
        var finalHandler = (IRequestPipelineDelegate<global::Some.Nested.Types.Program.Ping, global::Some.Nested.Types.Program.Pong>)handler.Handle;
        foreach (var pipeline in behaviors.Reverse())
        {
            var handlerCopy = finalHandler;
            var pipelineCopy = pipeline;
            finalHandler = (global::Some.Nested.Types.Program.Ping request, CancellationToken cancellationToken) => pipelineCopy.Handle(request, handlerCopy, cancellationToken);
        }
        this.handler = finalHandler;
    }

    public ValueTask<global::Some.Nested.Types.Program.Pong> Handle(global::Some.Nested.Types.Program.Ping request, CancellationToken cancellationToken = default)
    {
        return handler(request, cancellationToken);
    }
}

#nullable disable
