//HintName: Ravitor_Test_Integration_InsideClass_PingHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Ravitor.Generator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Ravitor.Contracts.Handlers;
using Ravitor.Contracts.Pipelines;
using Microsoft.Extensions.DependencyInjection;

namespace Ravitor.Generator.Ravitor.Test.Integration;

internal sealed class InsideClass_PingHandlerWrapper : IRequestHandler<global::Ravitor.Test.Integration.InsideClass.Ping, global::Ravitor.Test.Integration.InsideClass.Pong>
{
    private readonly IRequestPipelineDelegate<global::Ravitor.Test.Integration.InsideClass.Ping, global::Ravitor.Test.Integration.InsideClass.Pong> handler;

    public InsideClass_PingHandlerWrapper(
        global::Ravitor.Test.Integration.InsideClass.PingHandler handler,
        IEnumerable<IRequestPipeline<global::Ravitor.Test.Integration.InsideClass.Ping, global::Ravitor.Test.Integration.InsideClass.Pong>> behaviors)
    {
        var finalHandler = (IRequestPipelineDelegate<global::Ravitor.Test.Integration.InsideClass.Ping, global::Ravitor.Test.Integration.InsideClass.Pong>)handler.Handle;
        foreach (var pipeline in behaviors.Reverse())
        {
            var handlerCopy = finalHandler;
            var pipelineCopy = pipeline;
            finalHandler = (global::Ravitor.Test.Integration.InsideClass.Ping request, CancellationToken cancellationToken) => pipelineCopy.Handle(request, handlerCopy, cancellationToken);
        }
        this.handler = finalHandler;
    }

    public ValueTask<global::Ravitor.Test.Integration.InsideClass.Pong> Handle(global::Ravitor.Test.Integration.InsideClass.Ping request, CancellationToken cancellationToken = default)
    {
        return handler(request, cancellationToken);
    }
}

#nullable disable
