//HintName: _Interceptor.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Ravitor.Generator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using Ravitor.Contracts.Requests;
using Microsoft.Extensions.DependencyInjection;

namespace System.Runtime.CompilerServices
{
    [Conditional("DEBUG")] // not needed post-build, so can evaporate it
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    sealed file class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}

namespace Ravitor.Interceptor
{
    static file class Interceptors
    {
        [InterceptsLocation(1, "uaO0vLSgp7NZjfwatzTT21kCAAA=")] // (24,20)
        public static ValueTask<TResponse> Send_Ping<TResponse>(this global::Ravitor.Contracts.IMediator sender, IRequest<TResponse> request, CancellationToken cancellationToken = default)
        {
            var rqst = request as global::Ping;
            var task = sender.Send<global::Ping, global::Pong>(rqst!, cancellationToken);
            return Unsafe.As<ValueTask<global::Pong>, ValueTask<TResponse>>(ref task);
        }

    }
}

#nullable disable
