//HintName: _Interceptor.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Ravitor.Generator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using Ravitor.Contracts.Requests;
using Microsoft.Extensions.DependencyInjection;

namespace System.Runtime.CompilerServices
{
    [Conditional("DEBUG")] // not needed post-build, so can evaporate it
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    sealed file class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}

namespace Ravitor.Generator
{
    static file class Interceptors
    {
        [InterceptsLocation(1, "C4YPF92gqUOHAGRfrajXoOoCAAA=")] // (28,35)
        public static ValueTask<TResponse> Send_Ravitor_Test_Integration_Ping<TResponse>(this global::Ravitor.Contracts.ISender sender, IRequest<TResponse> request, CancellationToken cancellationToken = default)
        {
            var rqst = request as global::Ravitor.Test.Integration.Ping;
            var task = sender.Send<global::Ravitor.Test.Integration.Ping, global::Ravitor.Test.Integration.Result<global::Ravitor.Test.Integration.Pong>>(rqst!, cancellationToken);
            return Unsafe.As<ValueTask<global::Ravitor.Test.Integration.Result<global::Ravitor.Test.Integration.Pong>>, ValueTask<TResponse>>(ref task);
        }

    }
}

#nullable disable
