//HintName: Ravitor_Test_Integration_PingCommandHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Ravitor.Generator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Ravitor.Contracts.Handlers;
using Ravitor.Contracts.Pipelines;
using Microsoft.Extensions.DependencyInjection;

namespace Ravitor.Generator.Ravitor.Test.Integration;

internal sealed class PingCommandHandlerWrapper : IRequestHandler<global::Ravitor.Test.Integration.Ping, global::Ravitor.Test.Integration.Result<global::Ravitor.Test.Integration.Pong>>
{
    private readonly IRequestPipelineDelegate<global::Ravitor.Test.Integration.Ping, global::Ravitor.Test.Integration.Result<global::Ravitor.Test.Integration.Pong>> handler;

    public PingCommandHandlerWrapper(
        global::Ravitor.Test.Integration.PingCommandHandler handler,
        IEnumerable<IRequestPipeline<global::Ravitor.Test.Integration.Ping, global::Ravitor.Test.Integration.Result<global::Ravitor.Test.Integration.Pong>>> behaviors)
    {
        var finalHandler = (IRequestPipelineDelegate<global::Ravitor.Test.Integration.Ping, global::Ravitor.Test.Integration.Result<global::Ravitor.Test.Integration.Pong>>)handler.Handle;
        foreach (var pipeline in behaviors.Reverse())
        {
            var handlerCopy = finalHandler;
            var pipelineCopy = pipeline;
            finalHandler = (global::Ravitor.Test.Integration.Ping request, CancellationToken cancellationToken) => pipelineCopy.Handle(request, handlerCopy, cancellationToken);
        }
        this.handler = finalHandler;
    }

    public ValueTask<global::Ravitor.Test.Integration.Result<global::Ravitor.Test.Integration.Pong>> Handle(global::Ravitor.Test.Integration.Ping request, CancellationToken cancellationToken = default)
    {
        return handler(request, cancellationToken);
    }
}

#nullable disable
